### LOCAL - Get all
GET http://localhost:8080/contacts

### RENDER - Get all
GET https://cse341-contacts-api-fjj4.onrender.com/contacts

### LOCAL - Get one (replace id)
GET http://localhost:8080/contacts/<id>

### RENDER - Get one (replace id)
GET https://cse341-contacts-api-fjj4.onrender.com/contacts/<id>


