### =========================
### LOCAL – GET all contacts
### =========================
GET http://localhost:8080/contacts


### =========================
### RENDER – GET all contacts
### =========================
GET https://cse341-contacts-api-fjj4.onrender.com/contacts


### =========================
### LOCAL – GET one contact
### =========================
GET http://localhost:8080/contacts/<REAL_ID>


### =========================
### RENDER – GET one contact
### =========================
GET https://cse341-contacts-api-fjj4.onrender.com/contacts/<REAL_ID>


### =========================
### LOCAL – POST create contact
### =========================
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "firstName": "Week2",
  "lastName": "REST",
  "email": "week2rest@gmail.com",
  "favoriteColor": "Blue",
  "birthday": "2001-01-01"
}


### =========================
### RENDER – POST create contact
### =========================
POST https://cse341-contacts-api-fjj4.onrender.com/contacts
Content-Type:
